- archive subcommand enabled at usbfadm - boot mode 3 for archived data at /boottmp/rc  (gzip added to a crunched binary, etc.)

diff --git a/rdroot/boottmp/rc b/rdroot/boottmp/rc
--- a/rdroot/boottmp/rc
+++ b/rdroot/boottmp/rc
@@ -97,11 +97,11 @@ scan_disks () {
                     fi
                     if [ -r /mnt/livecd-config/${osrel}/${osmac}/noasks ]; then
                         # set local parameters to null
-                        local noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdir  # define local parameters
-                        unset noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdir  # after unset, they become global
-                        local noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdir  # so redefine them as local
+                        local noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdata  # define local parameters
+                        unset noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdata  # after unset, they become global
+                        local noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdata  # so redefine them as local
                         . /mnt/livecd-config/${osrel}/${osmac}/noasks
-                        if [ "X${noask_rdev}${noask_umem}${noask_setup_rw_mode}${noask_confdev}${noask_confdir}" != X ]; then
+                        if [ "X${noask_rdev}${noask_umem}${noask_setup_rw_mode}${noask_confdev}${noask_confdata}" != X ]; then
                             # any of noask parameters is set
                             part_noask=${part_noask:+"$part_noask "}${part}:/livecd-config/${osrel}/${osmac}/noasks
                         fi
@@ -345,8 +345,8 @@ fi
 #-------------------------------
 # wait for cancelling non-interactive boot
 #
-if [ "X${noask_rdev}${noask_umem}${noask_setup_rw_mode}${noask_confdev}${noask_confdir}" != X ]; then
-    trap "unset noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdir; echo ' ... cancelled'" 2
+if [ "X${noask_rdev}${noask_umem}${noask_setup_rw_mode}${noask_confdev}${noask_confdata}" != X ]; then
+    trap "unset noask_rdev noask_umem noask_setup_rw_mode noask_confdev noask_confdata; echo ' ... cancelled'" 2
     echo "Press ^C to cancel non-interactive boot"
     sleep 5
 fi
@@ -1066,21 +1066,22 @@ EOT
                      echo
                  fi)
                 echo -n 'config name -> '
-                if [ X = X"$noask_confdir" ]; then
-                    read confdir
+                if [ X = X"$noask_confdata" ]; then
+                    read confdata
                 else
-                    echo $noask_confdir
-                    confdir="$noask_confdir"
-                    noask_confdir=''
+                    echo $noask_confdata
+                    confdata="$noask_confdata"
+                    noask_confdata=''
                 fi
 
-                if [ X"$confdir" = X ]; then
+                if [ X"$confdata" = X ]; then
                     echo 'conf dir not specified'
                     umount "$usb_devname"
                     continue 2
-                elif [ -d /mnt/livecd-config/$osrel/$osmac/$confdir -o \
-                       -d /mnt/livecd-config/$confdir ]; then
-                    echo "$confdir" > /boottmp/boot_user_config
+                elif [ -d /mnt/livecd-config/$osrel/$osmac/$confdata -o \
+                       -f /mnt/livecd-config/$osrel/$osmac/$confdata -o \
+                       -d /mnt/livecd-config/$confdata ]; then
+                    echo "$confdata" > /boottmp/boot_user_config
                     break
                 else
                     echo 'cannot find such data'
@@ -1093,8 +1094,25 @@ EOT
             # copying to ram
             #
             echo "Copying files from persistent storage to ram ... "
-            if cd /mnt/livecd-config/$osrel/$osmac/$confdir 2> /dev/null || \
-               cd /mnt/livecd-config/$confdir; then
+            if [ -f /mnt/livecd-config/$osrel/$osmac/$confdata ]; then
+                if cd /ram; then
+                    # locate crunched binary gzip to temporary /usr/bin
+                    # because pax has fixed command search PATH in it.
+		    # gzip must be included in PATH
+                    mkdir -p /usr/bin
+                    ln -s /boottmp/gzip /usr/bin
+
+                    if ! pax -rzpe < /mnt/livecd-config/$osrel/$osmac/$confdata; then
+                        # tmpfs bug workaround
+                        # will retry later
+                        pax_arc_failed="yes"
+                    fi
+
+                    # cleanup temporary /usr/bin/gzip
+                    rm -rf /usr
+                fi
+            elif cd /mnt/livecd-config/$osrel/$osmac/$confdata 2> /dev/null || \
+               cd /mnt/livecd-config/$confdata; then
                 if ! pax -rwpe . /ram; then
                     # tmpfs bug workaround
                     # will retry later
@@ -1116,8 +1134,8 @@ EOT
             # retry copying to ram again
             #
             if [ "$pax_failed" = "yes" ]; then
-                if cd /mnt/livecd-config/$osrel/$osmac/$confdir 2> /dev/null || \
-                   cd /mnt/livecd-config/$confdir; then
+                if cd /mnt/livecd-config/$osrel/$osmac/$confdata 2> /dev/null || \
+                   cd /mnt/livecd-config/$confdata; then
                     for i in 1 2 3; do  # retry 3 time max
                         echo "Copying to ram was partially failed, retrying..."
                         if PATH=$PATH:/fuguita/usr/local/bin:/fuguita/usr/fuguita/bin \
