rc - retrieve user data from USB flash usbfadm - USB Flash ADMinistration tool

diff --git a/rdroot/boottmp/rc b/rdroot/boottmp/rc
--- a/rdroot/boottmp/rc
+++ b/rdroot/boottmp/rc
@@ -1,12 +1,21 @@
 #====================
+# interim rc file for LiveCD
+#
+# KAWAMATA, Yoshihiro
+# kaw@on.rim.or.jp
+#
+
+cd /
+
+#====================
 # setup file systems
 #
-cd /
 
 #-------------------------------
 # create fstab then mount by it
 #
 mount -w /dev/rd0a /
+: > /boottmp/boot_starts
 
 mfs_alloc_mb_max=$((`sysctl -n hw.usermem`/1024/1024))
 mfs_alloc_mb=$(($mfs_alloc_mb_max/2))
@@ -29,24 +38,24 @@ else
 =       please access http://kaw.ath.cx/openbsd/
 ================================================
 '
-    echo $mfs_alloc_mb_max MB of memory available for you.
+    echo "$mfs_alloc_mb_max MB of memory available for you."
     echo -n "your mfs size in megabytes? [default: $mfs_alloc_mb] -> "; read ans
 fi
 
 if [ X"$ans" != X ]; then
     mfs_alloc_mb=$ans
 fi
-echo Allocating $mfs_alloc_mb MB for mfs.
+echo "Allocating $mfs_alloc_mb MB for mfs."
 
-echo "/dev/rd0a	/	ffs	rw	0 0
-/dev/cd0c	/cdrom	cd9660	ro	0 0
-swap		/mfs	mfs	rw,async,-b=4096,-f=512,-i=1024,-s=$(($mfs_alloc_mb*1024*2)) 0 0" >/boottmp/fstab
+echo "/dev/rd0a /       ffs     rw      0 0
+/dev/cd0c       /cdrom  cd9660  ro      0 0
+swap            /mfs    mfs     rw,async,-b=4096,-f=512,-i=1024,-s=$(($mfs_alloc_mb*1024*2)) 0 0" >/boottmp/fstab
 
 if /sbin/mount -a; then
     :
 else
-    echo "Mount failed. Invoking shell to debug..."
-    /bin/sh
+    echo 'Mount failed.'
+    exit 1
 fi
 
 #----------------------------
@@ -55,107 +64,211 @@ fi
 /cdrom/bin/rm -rf /bin /sbin
 /cdrom/bin/ln -sf cdrom/bin cdrom/sbin .
 
-#-------------------------------------
-# copy CD-ROM contents to rw-able mfs
-#
-echo -n "Copying files from CD-ROM to mfs ... "
-cd /mfs
-(cd ../cdrom && tar cf - etc home tmp root var) | tar xpf -
-echo "done"
+setup_rw_mode=0
+echo 'Select boot method;'
+echo '   0: manual setup   (CD-ROM only)'
+echo '   1: with user data (copy from USB flash)'
+echo -n '-->'; read setup_rw_mode
 
-#-----------------------
-# symlink from / to mfs
-#
-cd /
-rm -rf /tmp
-mv /etc /bootetc
-ln -sf mfs/* .
-cp /boottmp/fstab /etc
+case X"$setup_rw_mode" in
+    X1)
+	echo "usbflash" > /boottmp/boot_mode
 
-#-------------------------------------------
-# symlink rest of contents from / to CD-ROM
-#
-ln -s cdrom/* .     2>/dev/null
-#ln -s cdrom/.??* . 2>/dev/null ; # Maybe not needed
+        #-----------------------
+        # search USB mass storage
+        # (works on a subshell not to destroy positional parameters...)
+        #
+	( set X `dmesg | while read ln; do case Y"$ln" in Yscsibus[0-9]" at "umass[0-9]*) echo $ln;; esac; done`
+	  if [ $# -gt 2 ]; then
+	      usb_scsi_umass=${2%:}
+	      usb_umass=$4
 
-#-------------------------------------------
-# lndir from /mfs/usr to /cdrom/usr
-#
-echo -n "Linking files from mfs to CD-ROM ... "
-mkdir /mfs/usr && cd /mfs/usr && lndir -s /cdrom/usr
+	      set X `dmesg | while read ln; do case Y"$ln" in Ysd[0-9]" at "scsibus[0-9]*) echo $ln;; esac; done`
+	      if [ $# -gt 2 ]; then
+		  usb_sd=$2
+		  usb_sd_scsi=$4
+		  if [ "$usb_scsi_umass" = "$usb_sd_scsi" ]; then
+		      echo "USB flash memory found as $usb_sd"
+		  else
+		      echo "SCSI bus between sd($usb_sd at $usb_sd_scsi) and umass($usb_scsi_umass at $usb_umass) not match"
+		      exit 1
+		  fi
+	      else
+		  echo 'SCSI-simulated USB disk storage not found'
+		  exit 1
+	      fi
+	  else
+	      echo 'USB mass storage device not found'
+	      exit 1
+	  fi
 
-#-------------------------------------------
-# Then, copy again for trivial dirs
-#
-for d in \
-    usr/libexec/auth \
-    usr/local/lib/wnn
-do
-    if [ -d /mfs/$d ]; then
-        rm -rf /mfs/$d && cd `dirname /cdrom/$d` && pax -rwpe `basename $d` `dirname /mfs/$d`
-    fi
-done
+	  usb_devname=/dev/${usb_sd}a
+	  echo "$usb_devname" > /boottmp/boot_restore_devname )
 
-cd / && ln -sf mfs/usr .
-echo "done"
+        #-----------------------
+        # mount user's storage
+        #
+	if mount -r `cat /boottmp/boot_restore_devname` /mnt; then
+	    #-----------------------
+	    # select config files
+	    #
+	    if [ ! -d /mnt/livecd-config ]; then
+		echo 'cannot find config dir'
+		exit 1
+	    fi
 
-#========================================
-# setup in /etc (network etc...)
-#
-echo ""
+	    while :; do
+	        echo 'avairable configs;'
+	        (cd /mnt/livecd-config && echo ""; ls -C; echo "")
+	        echo -n 'your config name? -> '; read confdir
+		if [ -d "/mnt/livecd-config/$confdir" ]; then
+		    echo "$confdir" > /boottmp/boot_user_config
+		    break
+		else
+		    echo 'cannot find config dir'
+		fi
+	    done
 
-echo "Set your keyboard type;"
-while :;
-do
-    echo -n `kbd -l`
-    echo -n ' -> '; read kbtype
-    if kbd $kbtype; then
-        echo $kbtype > /etc/kbdtype
-        break
-    fi
-done
+	    #-----------------------
+	    # symlink from / to mfs
+	    #
+            echo -n "Copying files from flash to mfs ... "
+            cd /mfs
+            (cd /mnt/livecd-config/$confdir && tar cf - .) | tar xpf -
+            echo "done"
 
-echo -n "Please wait ... "
-until passwd root
-do
-    echo "passwd failed, Try again."
-done
+	    #-----------------------
+	    # symlink from / to mfs
+	    #
+	    cd /
+	    rm -rf /tmp
+	    mv /etc /bootetc
+	    ln -sf mfs/* .
+	    cp /boottmp/fstab /etc
 
-echo -n 'Setting up network configurations? -> '; read ans
-case X"$ans" in
-    X[Yy])
-        echo "========================================"
-        ifconfig -a
-        echo "========================================"
-        echo -n 'your network interface ? -> '; read mynic
-        echo -n 'your IPv4 addr or "dhcp" ? -> '; read myv4addr
-        if [ X"$myv4addr" = Xdhcp ]; then
-            echo "dhcp" > /etc/hostname.$mynic
-        else
-            echo -n 'your netmask ? -> '; read mynetmask
-            echo -n 'your FQDN ? -> '; read myfqdn
-            echo -n 'your DNS server ? -> '; read mydns
-            echo -n 'your default gateway ? -> '; read mygw
+	    #-------------------------------------------
+	    # symlink rest of contents from / to CD-ROM
+	    #
+	    ln -s cdrom/* .     2>/dev/null
+	    #ln -s cdrom/.??* . 2>/dev/null ; # Maybe not needed
 
-            echo "inet $myv4addr $mynetmask NONE" > /etc/hostname.$mynic
-            echo "nameserver $mydns" > /etc/resolv.conf
-            echo "$myfqdn" > /etc/myname
-            echo "$mygw" > /etc/mygate
-        fi
+	    umount /mnt
+	else
+	    echo "Failed to mount user's storage"
+	    exit 1
+	fi
+    ;;
+    *)
+	echo "manual" > /boottmp/boot_mode
+
+        #-------------------------------------
+        # copy CD-ROM contents to rw-able mfs
+        #
+        echo "Running manual setup."
+        echo -n "Copying files from CD-ROM to mfs ... "
+        cd /mfs
+        (cd ../cdrom && tar cf - etc home tmp root var) | tar xpf -
+        echo "done"
+
+        #-----------------------
+        # symlink from / to mfs
+        #
+        cd /
+        rm -rf /tmp
+        mv /etc /bootetc
+        ln -sf mfs/* .
+        cp /boottmp/fstab /etc
+
+        #-------------------------------------------
+        # symlink rest of contents from / to CD-ROM
+        #
+        ln -s cdrom/* .     2>/dev/null
+        #ln -s cdrom/.??* . 2>/dev/null ; # Maybe not needed
+
+        #-------------------------------------------
+        # lndir from /mfs/usr to /cdrom/usr
+        #
+        echo -n "Linking files from mfs to CD-ROM ... "
+        mkdir /mfs/usr && cd /mfs/usr && lndir -s /cdrom/usr
+
+        #-------------------------------------------
+        # Then, copy again for trivial dirs
+        #
+        for d in \
+            usr/libexec/auth \
+            usr/local/lib/wnn
+        do
+            if [ -d /mfs/$d ]; then
+                rm -rf /mfs/$d && cd `dirname /cdrom/$d` && pax -rwpe `basename $d` `dirname /mfs/$d`
+            fi
+        done
+
+        cd / && ln -sf mfs/usr .
+        echo "done"
+
+        #========================================
+        # setup in /etc (network etc...)
+        #
+        echo ""
+
+        echo "Set your keyboard type;"
+        while :;
+        do
+            echo -n `kbd -l`
+            echo -n ' -> '; read kbtype
+            if kbd $kbtype; then
+                echo $kbtype > /etc/kbdtype
+                break
+            fi
+        done
+
+        echo -n "Please wait ... "
+        until passwd root
+        do
+            echo "passwd failed, Try again."
+        done
+
+        echo -n 'Setting up network configurations? -> '; read ans
+        case X"$ans" in
+            X[Yy])
+                echo "========================================"
+                ifconfig -a
+                echo "========================================"
+                echo -n 'your network interface? -> '; read mynic
+                echo -n 'your IPv4 addr or "dhcp"? -> '; read myv4addr
+                if [ X"$myv4addr" = Xdhcp ]; then
+                    echo "dhcp" > /etc/hostname.$mynic
+                else
+                    echo -n 'your netmask? -> '; read mynetmask
+                    echo -n 'your FQDN? -> '; read myfqdn
+                    echo -n 'your DNS server? -> '; read mydns
+                    echo -n 'your default gateway? -> '; read mygw
+
+                    echo "inet $myv4addr $mynetmask NONE" > /etc/hostname.$mynic
+                    echo "lookup file bind"  >  /etc/resolv.conf
+                    echo "nameserver $mydns" >> /etc/resolv.conf
+                    echo "$myfqdn" > /etc/myname
+                    echo "$mygw" > /etc/mygate
+                    echo "::1 localhost.localnet localhost"       >  /etc/hosts
+                    echo "127.0.0.1 localhost.localnet localhost" >> /etc/hosts
+                    echo "$myv4addr $myfqdn ${myfqdn%%.*}"        >> /etc/hosts
+                fi
+            ;;
+        esac
+
+        echo -n 'Generate cryptographic keys? -> '; read ans
+        case X"$ans" in
+            X[Yy])
+                rm -f /etc/ssh/*_key* /etc/isakmpd/private/local.key
+            ;;
+        esac
     ;;
 esac
 
-echo -n 'Generate cryptographic keys? -> '; read ans
-case X"$ans" in
-    X[Yy])
-        rm -f /etc/ssh/*_key* /etc/isakmpd/private/local.key
-    ;;
-esac
 echo "========================================"
-
-date > /boottmp/operation_starts
+date > /boottmp/boot_livecd_rc_ends
 
 #========================================
-# run original /etc/rc
+# chain original /etc/rc
 #
 . /etc/rc
