-show progressbar when pv installed -use pax instead of rsync at 1st sync

diff --git a/rdroot/boottmp/usbfadm b/rdroot/boottmp/usbfadm
--- a/rdroot/boottmp/usbfadm
+++ b/rdroot/boottmp/usbfadm
@@ -283,6 +283,24 @@ function sect2byte {
 }
 
 #-------------------
+# copy directory tree with progress display
+#
+# Usage: copydirs srcdir destdir
+#
+copydirs () {
+    local srcdir;  srcdir="$1"
+    local destdir; destdir="$2"
+    [ -d "$srcdir" ]  || { echo "source directory $srcdir not found";       return; }
+    [ -d "$destdir" ] || { echo "destination directory $destdir not found"; return; }
+    if [ -x /usr/local/bin/pv ]; then
+        pax -wX "$srcdir" | pv | ( cd "$destdir" && pax -rpe )
+    else
+        (while :; do sleep 15; pkill -INFO dd || exit; done) &
+        pax -wX "$srcdir" | dd bs=1m | ( cd "$destdir" && pax -rpe )
+    fi
+}
+
+#-------------------
 # scan specified disk
 # then outputs its parameters with form of sh var assignment
 #
@@ -353,7 +371,6 @@ function showparams {
     #    diskscan   : result of scan - 'ok' or 'ng'
     # 
     # partition sectors (ps_ for short)
-    #
     #    ps_free : available sectors for user's partitioning
     #    ps_hgap : head gap (for MBR/GPT and disklabel)
     #    ps_uefi : sectors for UEFI (partition i)
@@ -560,10 +577,14 @@ function setup_fs {
         (cd /sysmedia
          pax -rwvpe !(fuguita-${osrel}-${hwmac}.ffsimg) /mnt)
 
+        notice "Transferring filesystem image"
         if [ -r /sysmedia/fuguita-${osrel}-${hwmac}.ffsimg ]; then
-            notice "Transferring filesystem image"
-            (sleep 15; while pkill -INFO dd; do sleep 15; done) &  # to display progress
-            dd if=/sysmedia/fuguita-${osrel}-${hwmac}.ffsimg of=/mnt/fuguita-${osrel}-${hwmac}.ffsimg bs=1m
+            if [ -x /usr/local/bin/pv ]; then
+                pv /sysmedia/fuguita-${osrel}-${hwmac}.ffsimg | dd of=/mnt/fuguita-${osrel}-${hwmac}.ffsimg bs=1m
+            else
+                (while :; do sleep 15; pkill -INFO dd || exit; done) &  # to display progress
+                dd if=/sysmedia/fuguita-${osrel}-${hwmac}.ffsimg of=/mnt/fuguita-${osrel}-${hwmac}.ffsimg bs=1m
+            fi
         fi
 
         case $instsys in
@@ -762,10 +783,10 @@ if [ "$opt_mode" = 'resync' ]; then
 
     if mount -o softdep,noatime $devname /mnt; then
         if [ "$opt_quiet" = 'yes' ]; then
-            rsync -aqHxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
+            rsync -q -rlptgo --devices -HxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
         else
             notice "Sync current tmpfs as $uconf into $devname"
-            rsync --progress -avHxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
+            rsync --progress -rlptgo --devices -HxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
         fi
         # find /mnt \! -type d \! -type f \! -type l -print | xargs rm -f
         rm -rf /mnt/livecd-config/$uconf/tmp/{.??*,*}
@@ -835,10 +856,15 @@ while :; do
         fi
 
         if [ 1 = `ask_yn "Sync current tmpfs as \\\`\\\`$uconf'' , OK?" n` ]; then
-            if mount -o softdep,noatime $devname /mnt &&
-               mkdir -p /mnt/livecd-config/$verarch/$uconf; then
+            if mount -o softdep,noatime $devname /mnt; then
+
                 echo ''
-                rsync --progress -avHxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
+                if [ -d /mnt/livecd-config/$verarch/$uconf ]; then
+                    rsync -v -rlptgo --devices -HxS --delete --include '*/tmp' --exclude 'tmp/*' /ram/. /mnt/livecd-config/$verarch/$uconf/.
+                else
+                    mkdir -p /mnt/livecd-config/$verarch/$uconf
+                    (cd /ram; copydirs . /mnt/livecd-config/$verarch/$uconf)
+                fi
                 # find /mnt \! -type d \! -type f \! -type l -print | xargs rm -f
                 rm -rf /mnt/livecd-config/$verarch/$uconf/tmp/{.??*,*}
                 sync
@@ -991,11 +1017,18 @@ while :; do
                         [ 1 -le `ask_yn "$ans is very small value.\nDo you really take this value?" n` ] && break
                     fi
                 done
-                (sleep 15; while pkill -INFO dd; do sleep 15; done) &  # to display progress
-                if dd if=/dev/zero of=$vnfile bs=$sect_size count=`byte2sect $ans` && \
-                        vnconfig $newdev $vnfile; then
-                    :  # normal exit
+
+                if [ -x /usr/local/bin/pv ]; then
+                    sects=`byte2sect $ans`
+                    dd if=/dev/zero bs=$sect_size count=$sects | pv --size $((sect_size*sects)) > $vnfile && vnconfig $newdev $vnfile
+                    result=$?
                 else
+                    (while :; do sleep 15; pkill -INFO dd || exit 0; done) &  # to display progress
+                    dd if=/dev/zero of=$vnfile bs=$sect_size count=`byte2sect $ans` && vnconfig $newdev $vnfile
+                    result=$?
+                fi
+
+                if [ 0 -lt $result ]; then
                     clear_vn $newdev $vnfile
                     continue
                 fi
